### ISSUE TITLE
Agent style: range not working

### ISSUE THREAD

**Issue by warmdev** [Repast/repast.simphony#1]
Version: Repast 2.4
OS: Tested both Windows and OS X

To reproduce the problem:
* Import Geography demo model
* Run the model, and edit `A Display`, choose `Agent Style`, then `ZoneAgent`, then edit, then `Range Style`
* Change `Range Start` and `Range End`
* Change is not reflected in the symbol table below

**Comment by etatara** [comment]
You can work around this issue by hitting the Enter key while the cursor is in either the Range Start or Range End boxes and the symbol table will be updated.  We should fix the change listener in the dialog to automatically updated the table when new values are entered.

**Comment by jozik** [comment]
Won't fix.
