### ISSUE TITLE
Repast Simphony 2.5 in Ubuntu 17.04 and Eclipse Oxygen 1A not working

### ISSUE THREAD

**Issue by thalerjonathan** [Repast/repast.simphony#10]
I want to use Repast Simphony 2.5 on my Ubuntu 17.04 installation. I followed the instructions from https://repast.github.io/download.html but when I want to run the demonstration models imported from https://github.com/Repast/repast.simphony.models/archive/v.2.5.zip I can't because the path to the Repast Simphony Libraries is invalid / they are simply missing. I get the error "Invalid classpath container: 'Repast Simphony Development Libraries' in project XXX'".

Same error when using Neon.

**Comment by ncollier** [comment]
Does the Repast Simphony Perspective exist in Eclipse (Window -> Perspective->Open Perspective->Other)? If so, can you clean (Project->Clean) and refresh (Right click the project -> Refresh) the demo projects? This was tested on Ubuntu 16.04 but I wouldn't think that an Ubuntu version difference would cause the problem.

**Comment by thalerjonathan** [comment]
Yes the Repast Simphony Perspective exists. Cleaning and Refreshing does not help, still get the same error: Build path entry is missing: REPAST_SIMPHONY_SUPPORT.

**Comment by ncollier** [comment]
OK. Thanks. We are trying to track it down.

**Comment by etatara** [comment]
The cause of the null path entries is probably due to Eclipse installed to a system app folder location and the update site plugins are installed to a user folder.  The Repast plugins need to be installed in the /eclipse/plugins folder.  I would recommend unpacking eclipse to your user /home folder as this should install the update site plugins there.  Also make sure not to use any elevated admin priveledges (e.g. sudo) to install Eclipse or the same issue will happen if you try to run Eclipse as a user.

Also, we just updated the Repast update site this evening to address an issue with the groovy plugin for Eclipse so please try to install Repast again to make sure to get the latest changes.

**Comment by thalerjonathan** [comment]
I tried it now, still seems not to work. I have now directly downloaded the eclipse package instead of using an installer. I am NOT running as super-user. Here is what I do:

1. Download Eclipse Package for Linux 64 bit from http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/1a/eclipse-java-oxygen-1a-linux-gtk-x86_64.tar.gz
2. Unpack to my home folder with the path being now /home/jonathan/eclipse
3. Add http://download.eclipse.org/releases/neon as additional Software Site using Manage... as "Neon"
4. Installing Groovy stuff from http://dist.springsource.org/snapshot/GRECLIPSE/e4.7 only Extra Groovy Compilers, Groovy-Eclipse, Uncategorized (skipping Maven Support)
5. Installing RePast from https://repocafe.cels.anl.gov/repos/repast (includes accepting a certificate from Eclipse Foundation)
6. Download examples from https://github.com/Repast/repast.simphony.models/archive/v.2.5.zip and unpacking it in Downloads folder
7. Importing the examples using File -> Import -> Existing Projects into Workspace
8. Refreshing and Cleaning all Projects and wait for rebuild
9. All examples show the same Error e.g.: "Invalid classpath container: 'Repast Simphony Development Libraries' in project 'Autocatalysis'"

**Comment by etatara** [comment]
Jonathan,

You need to use the “Eclipse IDE for Eclipse Committers” which includes additional Eclipse plugins required for Repast.  The “Eclipse IDE for Java Developers” which you have specified in Step 1 is not the correct version.  Please use this download link for linux

http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/1a/eclipse-committers-oxygen-1a-linux-gtk-x86_64.tar.gz

eric

**Comment by ncollier** [comment]
I just tested this with a new Eclipse from the link Eric post above and it does work. I did have to "clean" to get rid of an error in the Statechart Zombies project but other than that, no problems. This was with Ubuntu 16.04.

**Comment by thalerjonathan** [comment]
Using “Eclipse IDE for Eclipse Committers” did the trick!
Sorry guys for my ignorance, I didn't read the instructions carefully enough and skiped over "Commiters" part. Thanks for great support!
