### ISSUE TITLE
Importing model to new REPAST version

### ISSUE THREAD

**Issue by Maziyark** [Repast/repast.simphony#11]
Hi all!
I'm trying to import a model developed in REPAST 2.3.1 to 2.5 by going to:
 File>import>General>Existing Project into workspace
Unfortunately, REPAST libraries are not imported automatically. (For instance the Grid Class etc... are not recognized).
Do you have any suggestions to fix this?
Best,
Maziyar

**Comment by jozik** [comment]
Does this occurs when you try to run the model and or at compile time?

**Comment by Maziyark** [comment]
No. Right after I import the model... I cannot see REPAST libraries in Package explorer.

**Comment by jozik** [comment]
I've just tried to import a 2.3.1 model into 2.5.0 and didn't see any problems on my end. Does the 2.3.1 model do something non-standard with, e.g., the bin_and_src.jar?

**Comment by Maziyark** [comment]
No, not at all

**Comment by jozik** [comment]
You shouldn't need to. What does your .classpath file look like?

**Comment by Maziyark** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="ABM/src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="output" path="ABM/bin"/>
</classpath>

**Comment by Maziyark** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="ABM/src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="output" path="ABM/bin"/>
</classpath>

```

**Comment by Maziyark** [comment]
Thank you! That was it!
