### ISSUE TITLE
Repast Simphony 2.5 in Ubuntu 16.04 and Eclipse Oxygen 1A not working

### ISSUE THREAD

**Issue by RoyalCcc** [Repast/repast.simphony#12]
I want to use Repast Simphony 2.5 on my Ubuntu 16.04 installation. I followed the instructions from https://repast.github.io/download.html but when I want to run the demonstration Zombies_Demo models imported from https://github.com/Repast/repast.simphony.models/archive/v.2.5.zip
I get the error "Errors occured during the build. Errors running builder 'ReLogo Builder' on project 'Zombies_Demo'. groovy/utli/XmlSlurper'"
The only difference between instruction and what I done is when I installing Groovy stuff from http://dist.springsource.org/snapshot/GRECLIPSE/e4.7 only Extra Groovy Compilers, Groovy-Eclipse, Uncategorized, I can only found Main Package, Maven Support, More Compilers(I install skipping Maven Support)

**Comment by jozik** [comment]
Sorry, can you clarify what you **were** able to install from the GRECLIPSE site?

**Comment by RoyalCcc** [comment]
From GRECLIPSE I can only found and installed Main Package which include 'Eclipse Groovy Development Tools' , More Compilers which include 'Groovy Compiler 2.4/2.5/2.6' and Maven Support which I did not installed. But the instruction suggested me to install Extra Groovy Compilers, Groovy-Eclipse, Uncategorized. Those three I did not find.

**Comment by jozik** [comment]
Okay, thanks for the clarification. And just to make sure, you installed this version of Eclipse?
Eclipse IDE for **Eclipse Committers** Oxygen 1a: http://www.eclipse.org/downloads/packages/eclipse-ide-eclipse-committers/oxygen1a

**Comment by RoyalCcc** [comment]
Thanks a lot, by the way. I am using Ubuntu 16.04 64-bit
