### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by stefaneidelloth** [Repast/repast.simphony#16]
The FAQ states that following warning can savely be ignored. Nevertheless, I suggest to update xstream, which might resolve the issue. 

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/D:/EclipseJava/App/Eclipse/plugins/repast.simphony.runtime_2.6.0/lib/xstream-1.4.7.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

I use Eclipse 2018-12 and Open JDK 11.0.2 and installed the Groovy and Repast plugins using update pages.

**Comment by etatara** [comment]
This is a benign warning due to some of the third party libraries not being fully JDK 9+ module compliant.
