### ISSUE TITLE
How to remotly control Repast with Java API?

### ISSUE THREAD

**Issue by stefaneidelloth** [Repast/repast.simphony#18]
I would like to implement a connector for the EMA workbench:
https://github.com/quaquel/EMAworkbench/issues/52

What is the right starting point in the Java API to 
* load a Repast model
* set some variable values using the API 
* run the model
* return some results

I found 
repast.simphony.batch.BatchMain 
and
repast.simphony.runtime.RepastBatchMain
but they seem to be for a different purpose because they load the values from *.xml files?
 
=>What is the recommended way to remotely control a Repast model?
=> Do you have some example for doing so?

**Comment by jozik** [comment]
The [InstanceRunner class](https://repast.github.io/docs/api/repast_simphony/repast/simphony/batch/InstanceRunner.html) should do the trick.

You can take a look at the [Repast Simphony Batch Runs Getting Started Guide] (http://repast.sourceforge.net/docs/RepastBatchRunsGettingStarted.pdf) for how to create a "payload" which includes all the necessary Repast Simphony jars. You can look at repastwrapper.sh within the payload (see Section 8) and adapt the contents to launching a single run using the InstanceRunner class.
Something like:
    mkdir $instanceDir
    cd $instanceDir
    ln -s "../data" data
    java -Xmx512m -cp "../lib/*" repast.simphony.batch.InstanceRunner \
        -pxml ../scenario.rs/batch_params.xml \
        -scenario ../scenario.rs \
        -id $instance \
        -pinput localParamFile.txt

where the instanceDir variable is the directory within which the simulation will run and the localParamFile.txt is an unrolled parameter file specifying the combination(s) of parameters to run (see the unrolledParamFile.txt within the payload for an example). 

In case you don't want to create files for the parameters to run, if no -pinput then last arg is expected to be a string in unrolled parameter format. A parameter line has the format R\tP1\tV1,P2\tV2,P3\tV3,... R is the run number followed by a tab. P* and V* is a parameter name and value pair which are separated from each other by a tab and from other PV pairs by a comma delimeter.

**Comment by stefaneidelloth** [comment]
Thanks a lot! 

The InstanceRunner seems to parse the parameter String to a Parameters object and pass those parameters to `OneRunBatchRunner`. 

The OneBatchRunner tries to load a resource batch.properties:

`InputStream in = getClass().getResourceAsStream("batch.properties");`

and I get following error:

```
Exception in thread "main" java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.Properties.load(Properties.java:403)
	at repast.simphony.batch.OneRunBatchRunner.createScenarioLoader(OneRunBatchRunner.java:65)
	at repast.simphony.batch.OneRunBatchRunner.init(OneRunBatchRunner.java:52)
	at repast.simphony.batch.OneRunBatchRunner.<init>(OneRunBatchRunner.java:47)
	at repast.simphony.batch.InstanceRunner.configure(InstanceRunner.java:159)
	at jzombies.RepastRunner.main(RepastRunner.java:25)
```

I created a source folder "resources" to my Eclipse project and created an empty dummy file "batch.properties". However, that does not work. Maybe the batch.properties file needs to be somehow included in repast.simphony.distributed.batch.jar ?

=>How can I overcome that issue?




Further nodes:

* InstanceRunner contains a hard coded path to a batch configuration file. One has to make sure that that file exists:

` File in = new File("../MessageCenter.log4j.properties");`

* In principle, the InstanceRunner can be called with its main method that executes

```
InstanceRunner runner = new InstanceRunner();
runner.configure(args);
runner.run();
```
and those steps can also be called individually, so that the InstanceRunner only needs to be constructed once.

```
InstanceRunner runner = new InstanceRunner();
runner.configure(args1);
runner.run();
runner.configure(args2);
runner.run();
```

**Comment by stefaneidelloth** [comment]
Inside the OneRunBatchRunner the run method is:

```
public void run(int runNum, Parameters params) {
    pause = true;
    params = setupSweep(params);
    controller.runParameterSetters(params);
    controller.setRunNumber(runNum);
    controller.runInitialize(params);
    controller.execute();
    waitForRun();
    controller.runCleanup();
  }
```

Is it possible to use that controller to access DataSets to extract some reslts from the run?

**Comment by ncollier** [comment]
The simphony batch mechanism writes all the results gather by a DataSet to a file(s) through a FileSink. The DataSets do not store the results in memory, only passing the output on to DataSinks. So, you could write a DataSink implementation that stores data set output in memory where you could do something with it. 

There's some info on writing your own DataSink here:

http://repast.10935.n7.nabble.com/Data-Sinks-conditional-enable-disable-td9871.html

Alternatively, if you could wait until the run is over and gather the output from files. The output path is specified in the file_sink xml files in the projects .rs directory.

**Comment by stefaneidelloth** [comment]
Thank you for clarification. I would like to avoid file IO, if possible, because I would expect longer run times and possible complication for parallel runs. 

The strategy I would like to follow is:

* Pass input parameters and output/dataset-identifiers to my RepastRunner
* Get an instance of the above mentioned controller and access the DataSetManager
* Loop through the DataSet(-Builders) and try to find the wanted ones.
* If a wanted DataSet exists, automatically attach an in-memory-DataSink. Otherwise log a warning, that the model does not yet include the wanted DataSet.
* Run the model. During execution output data will be collected in the in-memory DataSinks.
* My RepastRunner returns the content of the DataSinks as results (and NaN for the outputs that could not be retrieved).

**Comment by stefaneidelloth** [comment]
The tricky part seem to be the timing, when to add the DataSink. If I try to add it before 

`controller.batchInitialize()`

the CurrentRunState is not yet defined (which I need to access the DataSetManager).

If I try to add the DataSink after `batchInitializie`, the change does not have an effect and my custom `DataSink` is not called. 

The link about how to implement a custom DataSink used a `ModelInitializer` to add the sink at the right moment. I managed to do something similar with the controller before calling controller.batchInitialize():

```
var controllerRegistry = controller.getControllerRegistry();
	  var contextId = controllerRegistry.getMasterContextId();	  
	  var actionTree = controllerRegistry.getActionTree(contextId);
	  
	  actionTree.addNode(actionTree.getRoot(),new ControllerAction() {

		@Override
		public void batchInitialize(RunState runState, Object contextId) {
			 var dataSetRegistry = (DataSetRegistry)runState.getFromRegistry(DataConstants.REGISTRY_KEY);
		      var dataSetManager = dataSetRegistry.getDataSetManager(contextId);		      
		            
		      var dataSetBuilder = dataSetManager.getDataSetBuilder("Agent Counts");   
		      
		      var dataSink = new DataSink() {

		  		@Override
		  		public void open(List<String> sourceIds) {
		  			System.out.println("open");
		  		}

		  		@Override
		  		public void rowStarted() {
		  			System.out.println("rowStarted");
		  		}

		  		@Override
		  		public void append(String key, Object value) {
		  			System.out.println("append");
		  		}

		  		@Override
		  		public void rowEnded() {
		  			System.out.println("rowEnded");
		  		}

		  		@Override
		  		public void recordEnded() {
		  			System.out.println("recordEnded");
		  		}

		  		@Override
		  		public void flush() {
		  			System.out.println("flush");
		  		}

		  		@Override
		  		public void close() {
		  			System.out.println("close");
		  		}		
		      	
		      };
		      
		      dataSetBuilder.addDataSink(dataSink); 
			
		}

		@Override
		public void runInitialize(RunState runState, Object contextId, Parameters runParams) {}

		@Override
		public void runCleanup(RunState runState, Object contextId) {}	

		@Override
		public void batchCleanup(RunState runState, Object contextId) {}
		  
	  });  	 
```

**Comment by stefaneidelloth** [comment]
Here is a first draft that works (also see attached text files). 

@ncollier 
Would it be interesting for you to include such connector code in the repast repository? Or should I put it in the ema workbench project?

[EmaRepastRunner.txt](https://github.com/Repast/repast.simphony/files/3039260/EmaRepastRunner.txt)
[EmaInstanceRunner.txt](https://github.com/Repast/repast.simphony/files/3039263/EmaInstanceRunner.txt)
[EmaOneRunBatchRunner.txt](https://github.com/Repast/repast.simphony/files/3039264/EmaOneRunBatchRunner.txt)


`package ema;

import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import repast.simphony.scenario.ScenarioLoadException;

public class EmaRepastRunner {

	public static void main(String[] args) throws IOException {

		var projectPath = ".";
		var scenarioFolderPath = projectPath + "/JZombies_Demo.rs";
		var parameterFilePath = projectPath + "/batch/batch_params.xml";
		var instanceId = "myInstanceId";

		var inputs = new HashMap<String, Integer>();
		inputs.put("zombie_count", 10);
		inputs.put("human_count", 20);

		var outcomes = Arrays.asList( //
				"Agent Counts.run1", //
				"Agent Counts.tick", //
				"Agent Counts.Human Count", //
				"Agent Counts.Zombie Count" //
		);

		var result = run(scenarioFolderPath, parameterFilePath, instanceId, inputs, outcomes);

		System.out.println(result);

	}

	public static Map<String, List<Double>> run(String scenarioFolderPath, String parameterFilePath, String instanceId,
			Map<String, ? extends Number> inputs, List<String> outcomes) throws IOException {

		var parameterString = "1\t" //
				+ inputs.entrySet() //
						.stream() //
						.map(entry -> entry.getKey() + "\t" + entry.getValue()) //
						.collect(Collectors.joining(",")); 
		
		var instanceRunner = new EmaInstanceRunner();

		try {
			instanceRunner.configure(new String[] { //
					"-pxml=" + parameterFilePath, //
					"-scenario=" + scenarioFolderPath, //
					"-id=" + instanceId, //
					parameterString });
		} catch (ScenarioLoadException exception) {
			var message = "Could not configure InstanceRunner with scenario folder '" + scenarioFolderPath + "' and"
					+ "parameter string '" + parameterString + "'.";
			throw new IllegalStateException(message, exception);
		}

		Map<String, List<Double>> result = null;
		try {
			result = instanceRunner.run(outcomes);
		} catch (ScenarioLoadException exception) {
			var message = "Could not run InstanceRunner with scenario folder '" + scenarioFolderPath + "' and"
					+ "parameter string '" + parameterString + "'.";
			throw new IllegalStateException(message, exception);
		}

		return result;
	}

}
`

**Comment by ncollier** [comment]
Glad you got it working. At the very least we should add this as an example to our documentation for how to do a single run and gather and return results in memory via the API. The code could also become part of repast itself.

**Comment by jozik** [comment]
One point that might make the classpath that you maintain more simple, if you use the jars produced within the lib directory of the "payload" I referred to above (except for the model.jar which would be in your project already). Also you wouldn't have to create your own EmaOneRunBatchRunner since one of the jars does contain the batch.properties file.

One underlying assumption that we made when creating the InstanceRunner was that you would not be running it from within a Repast project, but if it's just a matter of including the missing batch.properties file (or removing the need for one), we will make a point of including this functionality in the next release.

**Comment by stefaneidelloth** [comment]
Thank you for clarification. 

* My EmaOneRunBatchRunner includes a getter for the controller to allow my EmaInstanceRunner to access the DataSetManager. Maybe it would be a good to add a getter to the original OneRunBatchRunner or to make its properties protected to allow for inheritance.
 
* I updated my above example code to include the python part for the EMA workbench connector.

* If I understand you correctly, you suggestion is to use the button"Create Model Archive for Batch Runs" of the batch gui to create ./output/complete_model.jar and to reference that single "payload" jar file instead of including all individual jars in the lib folder. That works in principle and it reduces the number of jar files.  However, it did not solve the batch.properties issue for me. Where should the batch.properties file be located in the complete_model.jar archive?

**Comment by jozik** [comment]
> If I understand you correctly, your suggestion is to use the button"Create Model Archive for Batch Runs" of the batch gui to create ./output/complete_model.jar and to reference that single "payload" jar file instead of including all individual jars in the lib folder. That works in principle and it simplifies the class path a bit. However, it did not solve the batch.properties issue for me. Where exactly should the batch.properties file be located in the complete_model.jar archive? I could not find it.

Sorry, let me clarify further. The complete_model.jar is an archive containing elements that are unarchived (see 8. Running on a Cluster or HPC Machine in the [Repast Batch Runs Getting Started](https://repast.github.io/docs/RepastBatchRunsGettingStarted.pdf)). Once unzipped, you'll find a lib directory with a number of jars in it. These are the small number of jars (excluding the model.jar if you already have your model's classpath included) that you can put on your classpath, which will include the batch.properties file.

**Comment by jozik** [comment]
Closing this but let us know if it needs further discussion.
