### ISSUE TITLE
Eclipse plugin installation will not fetch all necessary dependencies

### ISSUE THREAD

**Issue by erkinalp** [Repast/repast.simphony#2]

**Comment by etatara** [comment]
The Groovy Eclipse plugin must be installed before the Repast plugin if that's the error you are getting.  Please see the section "Linux users" in the documentation https://repast.github.io/download.html for more info.  This installation for the Repast Eclipse plugin works the same on all operating systems.  Once the groovy plugin is installed, the Repast update site plugin will fetch all dependencies.

**Comment by etatara** [comment]
It seems like the eclipse.org site is experiencing technical issues since I can't even get through to download a copy.

**Comment by erkinalp** [comment]
I had been confronted in a situation where installing Groovy-Eclipse would cause to remove Repast and vice versa.

**Comment by etatara** [comment]
Could you please provide specific details to reproduce this issue?

**Comment by erkinalp** [comment]
Install groovy-eclipse from https://github.com/groovy/groovy-eclipse/commit/ed81c0d1c0ed7c43374f7b1745ba756e03d34d80.(Current version does not have this issue). Then try installing Repast from ANL-external repo.

**Comment by jozik** [comment]
Should be resolved.
