### ISSUE TITLE
Cannot satisfy dependency

### ISSUE THREAD

**Issue by raikon55** [Repast/repast.simphony#20]
Hello, I trying install repast simphony on Eclipse Committers Neon, but i receive some errors.

I tried install repast on several versions of eclipse, groovy and another linux system (Manjaro), but it always return the same error.

**The error**
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Repast Simphony 2.6.0 (repast.simphony.feature.feature.group 2.6.0)
  Missing requirement: Repast relogo ide 2.6.0 (repast.simphony.relogo.ide 2.6.0) requires 'osgi.bundle; org.codehaus.groovy.eclipse.codeassist.completion 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Repast Simphony 2.6.0 (repast.simphony.feature.feature.group 2.6.0)
    To: org.eclipse.equinox.p2.iu; repast.simphony.relogo.ide [2.6.0,2.6.0]
```

I'm using 
* GNU/Debian testing
* OpenJDK 8
* groovy-eclipse 4.6
and I trying install repast 2.6.

openjdk version "1.8.0_222-ea"
OpenJDK Runtime Environment (build 1.8.0_222-ea-8u222-b07-3-b07)
OpenJDK 64-Bit Server VM (build 25.222-b07, mixed mode)

**Comment by jozik** [comment]
Are you seeing this error after trying to follow these instructions: https://repast.github.io/download.html#update-site-install ?

**Comment by raikon55** [comment]
Yes, I was follow the guide step by step.

**Comment by etatara** [comment]
Repast 2.6 requires Eclipse IDE for Eclipse Committers 2018-09 or later.  It will not work with Neon.

**Comment by raikon55** [comment]
I installed using Eclipse Committers 2018-09 and it give the same error. I'm trying install repast on Eclipse has 3 days, I used eclipse, groovy, repast in older versions and nothing works. In eclipse's plugins directory, I found it 'org.codehaus.groovy.eclipse.codeassist_3.4.0.v201906292136-e1906-RELEASE.jar',

**Comment by jozik** [comment]
I'm seeing this now as well on a macOS install. We'll take a look and see what's causing this.

**Comment by etatara** [comment]
Thanks for the clarification and letting us know about this issue.  It seems that the Groovy Eclipse update site URL has change without notice.  Please use the following update site **https://dist.springsource.org/release/GRECLIPSE/3.1.0/e4.9** with  Eclipse IDE for Eclipse Committers **2018-09**.  Please note that Repast 2.6 requires GRECLIPSE version 3.1 which appears to be only available for Eclipse 2018-09 and NOT later versions.

**Comment by jozik** [comment]
Great, thank you Eric. I've updated the documentation to reflect this: https://repast.github.io/download.html#update-site-install

**Comment by raikon55** [comment]
I'm going to use Committers 2018-09 version and GRECLIPSE 2.6 .
Thanks a lot for the help! :D
