### ISSUE TITLE
Best way to create a neighborhood in repast.simphony.space.gis.Geography

### ISSUE THREAD

**Issue by swapna6** [Repast/repast.simphony#21]
I have created a Geography (repast.simphony.space.gis.Geography) object which holds my raster files, shapefiles and agents. At some point in the simulation, I need to find cells OR locations(lat,long) from a specified point location(lat,long).
E.g. Get all cells OR locations(lat,long) at a distance 25km from current point(lat/long).

A few ways of doing this are:
Opt 1. Get a Moore Neighborhood/Grid Neighborhood around the current point at the specified distance.
Opt 2. Draw a circle around the current point at the specified distance. Then get all (lat,long) positions on the circumference with a gap of 1km.

Are there any APIs in Repast Java that I can use for Opt 1 or Opt 2. If not, is there any other easier way to compute this?

**Comment by etatara** [comment]
Hi, thanks for your interest in using Repast.  Please post modeling questions on the Repast mail list or on StackOverflow as described in the Support documentation.  We will answer questions, however the Github issues is for reporting problems with Repast itself.
