### ISSUE TITLE
How to create a MooreNeighborhood around a particular point in a GIS environment?

### ISSUE THREAD

**Issue by swapna6** [Repast/repast.simphony#22]
Hi ,

I am new to GIS modeling in Repast. I am not understanding how to retrieve Moore Neighborhood around a particular point (denoted by lat/long) located on a raster layer OR the GIS grid coverage. Also, is there a way that I can generate this neighborhood at certain distance from the center point.

Any help/reading material would be greatly appreciated.
Thanks!

**Comment by etatara** [comment]
Hi, thanks for your interest in using Repast.  Please post modeling questions on the Repast mail list or on StackOverflow as described in the Support documentation.  We will answer questions, however the Github issues is for reporting problems with Repast itself.
