### ISSUE TITLE
Aggregate Data Set Editor removes all "not recently added" sources when pressing apply all

### ISSUE THREAD

**Issue by MelchiorUU** [Repast/repast.simphony#26]
In the repast gui you can edit data sets. One way to do this is the aggregate data set editor. I have configured one and want to edit the data sources later in the project as I go on developing the model.

When you open an existing Data Set, go to the "Select Data Sources" tab you see your data sources. If you press "Apply all" and ok, without doing anything else, you get no visual feedback. If you then try to edit a chart with the edited data source you get nullpointer exceptions. When you then inspect your data set again you see that all your data sources are gone.

If you happen to have added a data source before pressing "apply all" and ok, you only see those data sources left.

Summary: pressing apply all and ok seems to remove all existing data sources from a data set. 

Issue with Repast 2.7.

**Comment by jozik** [comment]
Thanks for pointing this out. This is a known issue that we will fix. In the meantime, we'd advise against using Apply All.

**Comment by ncollier** [comment]
Issue is with "Apply All". Clicking OK after adding or removing data sources works as expected.

**Comment by ncollier** [comment]
Disabled Apply All in OptionsDialog. OK does everything we need to do. See 527b987
