### ISSUE TITLE
Adding parameter in GUI removes other "extended" parameters

### ISSUE THREAD

**Issue by MelchiorUU** [Repast/repast.simphony#28]
In my parameters list I have a number of parameters that work with a range attribute. Range is an undocumented attribute in the standard repast simphony library. It also isn't represented in the GUI. You can only set it in the xml.

When I add another parameter the parameter with range attribute disappear. If I save the parameters I can see that the paramter that had the range attribute is still in the xml, but the range attribute has been removed. It seems as if there is some validation function that removes all attributes that do not comply to the GUI settable attributes.

Proposed solution:
* remove this validation or check.
* document and add range to the GUI.

**Comment by ncollier** [comment]
Thanks. We will look into this.

**Comment by ncollier** [comment]
Fixed disappearing range attributes: 4b4e24c
