### ISSUE TITLE
3D displays do not pan with right mouse button

### ISSUE THREAD

**Issue by etatara** [Repast/repast.simphony#30]
The 3D displays previously would pan with right mouse button click and drag, and now the mouse button 1+3 behavior is identical such that both buttons rotate the display.  Using Java 8 demonstrates the correct behavior while Java 11 does not so their may have been a mouse listener API change we need to account for.

The Java3D MouseZoom, MouseRotate, and MouseTranslate use deprecated or outdated mouse event API for detecting event types.  We should change thie mouse event type to use MouseEvent extended modifier and event bitmask checks.

- [x] Update Java3D mouse event classes
- [x] Test on Windows
- [x] Test on macOS
- [x] Test with JDK 8

**Comment by ncollier** [comment]
Fixed in e5a540d
