### ISSUE TITLE
repast simphony error

### ISSUE THREAD

**Issue by WangShuangyan** [Repast/repast.simphony#5]
Hi, I finished my code for java, but ,after I run the model, the repast shows that _Error while creats a display_, but I had set the display, What the problem? Is there a problem with my code?

Thank you for solving my issue

**Comment by ncollier** [comment]
Make sure the names of the context and projections as defined in the context.xml match those you assign to the projection etc. in the ContextBuilder. If that doesn't help, please post the stack trace.
