### ISSUE TITLE
Repast Simphony run time issue

### ISSUE THREAD

**Issue by WangShuangyan** [Repast/repast.simphony#6]
Hi, I'm using the version 1.2 of Repast Simphony, After I finish my flowchart according to the file named _Getting Started_ , Then I launch the model, but, the Console shows that"log4j:WARN No appenders could be found for logger (MessageCenter.INTERNAL.saf.core.runtime.Boot). log4j:WARN Please initialize the log4j system properly." and I can't see the Run time interface, Please tell me where is wrong, if I use the version 2.4, this issue doesn't exist.

**Comment by ncollier** [comment]
We no longer support version 1.2, but the Repast Simphony FAQ does address this issue in section 3.4:

https://repast.github.io/docs/RepastSimphonyFAQ.pdf

**Comment by WangShuangyan** [comment]
Thank you
