### ISSUE TITLE
Update IzPack to 5.1.3

### ISSUE THREAD

**Issue by jozik** [Repast/repast.simphony#69]
From Repast mailing list:

> Hi Eric,
> 
> I found the IzPack issue on their bugtracker. It is listed as having been fixed in 5.1.3. 
> 
> https://izpack.atlassian.net/browse/IZPACK-1588
> 
> I have tested the installer creation with 5.1.3 (by pointing to my 5.1.3 installation in the installation_coordinator.xml instead of the 5.1.2 distributed with repast) and have successfully installed from the setup.jar with both Java 11 and Java 17 (openjdk on Debian Linux).
> 
> I can create the installer with my local 5.1.3 installation for now but it would be great if the version included with Repast could be updated.
> 
> Best regards,
> 
> Jonas Andersen

**Comment by etatara** [comment]
I updated the IzPack files in r.s.Eclipse but still need to test that the generated setup.jar works with Java 11+

**Comment by etatara** [comment]
Testing complete.
