### ISSUE TITLE
Eclipse Repast Update Site not working?

### ISSUE THREAD

**Issue by thalerjonathan** [Repast/repast.simphony#8]
I want to install Repast Java on Linux. As instructed on https://repast.github.io/download.html I downloaded Eclipse (tried both Neon and the most recent Oxygen Version) and followed the instructions to install Repast from its update site: https://repo.anl-external.org/repos/repast/. It seems that this site is not working, Eclipse is pending forever and connecting to this site in a browser seems not to work as well.

**Comment by JohnSherwood7** [comment]
I ran into this the other week! My workaround was to google for an alternate, I used: https://repocafe.cels.anl.gov/repos/repast/

It worked out for me. Make sure you use Neon - I initially grabbed Oxygen by mistake and it didn't play nice. (I forget what the exact issues were...)

**Comment by thalerjonathan** [comment]
Thanks for the help. It works now!
