### ISSUE TITLE
Java 17 JVM Arguments for Batch Mode Runs

### ISSUE THREAD

**Issue by ncollier** [Repast/repast.simphony#86]
Add the required arguments for Java 17 to prevent IllegalAccess exceptions (e.g. --add-opens <module>/<package>=ALL-UNNAMED) when running in batch mode.

**Comment by ncollier** [comment]
Adding the above --add-exports to JZombies launch configurations fixes the issue. I'm going to try to contact the original poster and see if this solves it for him.

**Comment by jonas-andersen** [comment]
Adding those parameters to the launchers seems to fix the issue. For the distributed model (Builder Installer for <project>) I also had to add them to the start_model.bat and start_model.command files in the installer directory.

**Comment by etatara** [comment]
The Eclipse launch configuration for batch runs already includes these VM args.  We need to update the RS runtime launch config to include these via RSProjectConfigurator.VMARGS and .BATCH_VMARGS.  We should also update the start_model.bat and start_model.command in the r.s.eclipse/setupfiles/installer.

Apply fix to the following locations:
- [ ] RSProjectConfigurator.VMARGS
- [ ] r.s.eclipse/setupfiles/installer/start_model.bat
- [ ] r.s.eclipse/setupfiles/installer/start_model.command
- [ ] Demo model launch configuration and start_model.* files

**Comment by ncollier** [comment]
Working JVM options for Java 17:

```
-XX:+IgnoreUnrecognizedVMOptions
--add-opens java.base/java.lang.reflect=ALL-UNNAMED
--add-modules=ALL-SYSTEM
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED
--add-exports=java.desktop/sun.awt=ALL-UNNAMED
--add-exports=java.base/java.lang=ALL-UNNAMED
--add-opens java.base/java.util=ALL-UNNAMED
--add-exports=java.xml/com.sun.org.apache.xpath.internal.objects=ALL-UNNAMED
--add-exports=java.xml/com.sun.org.apache.xpath.internal=ALL-UNNAMED
--add-opens java.base/java.lang=ALL-UNNAMED
```

**Comment by ncollier** [comment]
vm args for bat and model files.

start_model.bat:

```
javaw -XX:+IgnoreUnrecognizedVMOptions --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-modules=ALL-SYSTEM --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-exports=java.xml/com.sun.org.apache.xpath.internal.objects=ALL-UNNAMED --add-exports=java.xml/com.sun.org.apache.xpath.internal=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -cp "%CP%" repast.simphony.runtime.RepastMain "./%SCENARIO_DIRECTORY%"
 ```

start_model.command:

```
java -XX:+IgnoreUnrecognizedVMOptions \
	--add-opens java.base/java.lang.reflect=ALL-UNNAMED \
    --add-modules=ALL-SYSTEM \
    --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED \
    --add-exports=java.desktop/sun.awt=ALL-UNNAMED \
    --add-exports=java.base/java.lang=ALL-UNNAMED \
    --add-opens java.base/java.util=ALL-UNNAMED \
    --add-exports=java.xml/com.sun.org.apache.xpath.internal.objects=ALL-UNNAMED \
    --add-exports=java.xml/com.sun.org.apache.xpath.internal=ALL-UNNAMED \
    --add-opens java.base/java.lang=ALL-UNNAMED \
     -cp "$CP" repast.simphony.runtime.RepastMain  "./%SCENARIO_DIRECTORY%"
```

**Comment by ncollier** [comment]
Updated repast simphony: 3cc7df65
Updated models:  https://github.com/Repast/repast.simphony.models/commit/fbc9f87538dc1999769282233041fc41f33b0e0e
