### ISSUE TITLE
how to use GeoJSON which maybe is a provice of China to show a display in repast simphony

### ISSUE THREAD

**Issue by Forever1Love** [Repast/repast.simphony#95]
Hello , Repast team

I am a studier of repast simphony. I use   repast simphony 2.4 version, now I want to use GeoJSON which maybe is a provice of China, I do not knjow how to do. Can you help me and give me a demo. I also see the reference of Repast Simphony . I find it is explained easily. so I need your help.

I also want to show a animated gif when I run a repast model. Can you give an example.

Thanks a lot,

Mr Wang

**Comment by etatara** [comment]
Hi, Repast Simphony does not support loading GeoJSON format.  However, you can convert a GeoJSON file to the standard ESRI shapefile using GIS software like QGIS or ArcGIS, and then load the shapefile using Repast like in the Geography demo.

**Comment by Forever1Love** [comment]
你的邮件已收到，谢谢，！
